version: '3.8'

services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02,user03,user04,user05
      - LDAP_PASSWORDS=pass1,pass2,pass3,pass4,pass5
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_LOGLEVEL=256
    networks:
      - my-network
    ports:
      - "1389:1389"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpassword
    command: start-dev --import-realm
    volumes:
      - ./config/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
