version: '3.8'

services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_USERS=${LDAP_USERS}
      - LDAP_PASSWORDS=${LDAP_PASSWORDS}
      - LDAP_ROOT=${LDAP_ROOT}
    networks:
      - my-network
    volumes:
      - openldap_data:/bitnami/openldap

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - my-network
    depends_on:
      - openldap

networks:
  my-network:
    driver: bridge

volumes:
  openldap_data:
