version: '3.8'

services:
  lldap:
    image: lldap/lldap:latest
    container_name: lldap
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./bootstrap:/bootstrap:ro
      - ./tls/tls.crt:/tls/tls.crt:ro
      - ./tls/tls.key:/tls/tls.key:ro
    environment:
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
      - LLDAP_LDAP_USER_DN=cn=admin,ou=people,dc=example,dc=com
      - LLDAP_LDAP_USER_PASS=AdminPass123
      - LLDAP_JWT_SECRET=ReplaceWithYourJWTSecret
      - LLDAP_KEY_SEED=ReplaceWithYourKeySeed

      - LLDAP_LDAPS_OPTIONS__ENABLED=true
      - LLDAP_LDAPS_OPTIONS__PORT=636
      - LLDAP_LDAPS_OPTIONS__CERT_FILE=/tls/tls.crt
      - LLDAP_LDAPS_OPTIONS__KEY_FILE=/tls/tls.key
    networks:
      - my-network
    ports:
      - "389:3890"
      - "636:6360"
      - "17170:17170"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpassword
    command: start-dev --import-realm
    volumes:
      - ./config/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
