version: "3.8"

services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS_OU=users
      - LDAP_USERS=user01,user02,user03,user04,user05
      - LDAP_PASSWORDS=pass1,pass2,pass3,pass4,pass5
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_LOGLEVEL=256
    networks:
      - my-network
    ports:
      - "1389:1389"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_LOGIN_DN: cn=admin,dc=example,dc=org
    networks:
      - my-network
    ports:
      - "8091:80"
    restart: unless-stopped
    depends_on:
      - openldap

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: chatops-backend
    networks:
      - my-network
    ports:
      - "8090:8080"
    depends_on:
      - openldap

  bot:
    build:
      context: ../bot
      dockerfile: Dockerfile
    container_name: chatops-bot
    env_file:
      - ../bot/.env
    networks:
      - my-network
    ports:
      - "5010:5000"
    depends_on:
      - openldap
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "90:80"
    depends_on:
      - backend
      - bot
    networks:
      - my-network

networks:
  my-network: